Avoid duplicated RPN code execuation across multiple clients
MobiFlight/MobiFlight-WASM-Module pull request #27
Opened 2024-03-15 20:23 UTC by cpuwolf

when multiple clients Add duplicated SimVar to WASM, WASM will smartly merge SimVars.

introduce new structure:

//RPN code execution for reading values in every frame
struct ReadRPNCode {
	std::string Code;
	//RetType: 0:float 1:integer 2:string
	int RetType;
	std::vector<SimVar> SimVars;
	std::vector<StringSimVar> StringSimVars;
};

2024-03-16 00:53 UTC, DocMoebiuz commented
i am currently at FSWeekend, i will be looking at this PR next week

2024-05-05 21:54 UTC, cpuwolf commented
@DocMoebiuz Could you take a look?

2024-05-05 21:56 UTC, DocMoebiuz commented
Not yet tbh :(

2024-05-05 21:56 UTC, DocMoebiuz commented
Does this work with strings too? yeah, looks like you are also treating strings.

How much of an impact is this? What did you see in FPS drop?

2024-05-05 23:06 UTC, cpuwolf commented
std::vector<SimVar> SimVars;
std::vector<StringSimVar> StringSimVars;

so string is considered in this change. I don't have direct evident to  see FPS drop, but this change will improve FPS when we have multiple clients

2024-09-04 21:14 UTC, DocMoebiuz requested changes
Sorry for the tardy review.

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	struct Client * clint;
```suggestion
	struct Client * client;
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	struct Client * clint;
```suggestion
	struct Client * client;
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	newSimVar.clint = client;
```suggestion
	newSimVar.client = client;
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	ReadRPNCode* pdupRpn = IsDuplicatedSimVar(code);
Please use more descriptive variable names.

```suggestion
	ReadRPNCode* DuplicatedRpnCode = GetDuplicatedRpnCodeOrNull(code);
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	if (pdupRpn) {
```suggestion
	if (DuplicatedRpnCode) {
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	newStringSimVar.clint = client;
```suggestion
	newStringSimVar.client = client;
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	ReadRPNCode* pdupRpn = IsDuplicatedSimVar(code);
```suggestion
	ReadRPNCode* DuplicatedRpnCode = GetDuplicatedRpnCodeOrNull(code);
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	if (pdupRpn) {
```suggestion
	if (DuplicatedRpnCode) {
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +	}
- Move/extract internal loops to methods with descriptive names to improve readability.
- Fix the `clint` typo.

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> -	std::string Name;
Why remove? This was valuable in all the different log messages for troubleshooting. Was it not?

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +		WriteSimVar(simVar, simVar.clint);
```suggestion
		WriteSimVar(simVar, simVar.client);
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +		std::cout << "MobiFlight[" << simVar.clint->Name.c_str() << "]: SimVar " << rpn.Code.c_str();
```suggestion
		std::cout << "MobiFlight[" << simVar.client->Name.c_str() << "]: SimVar " << rpn.Code.c_str();
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +		WriteSimVar(simVar, simVar.clint);
```suggestion
		WriteSimVar(simVar, simVar.client);
```

2024-09-04 21:14 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> +		std::cout << "MobiFlight[" << simVar.clint->Name.c_str() << "]: StringSimVar " << rpn.Code.c_str();
```suggestion
		std::cout << "MobiFlight[" << simVar.client->Name.c_str() << "]: StringSimVar " << rpn.Code.c_str();
```

2024-09-05 00:08 UTC, cpuwolf commented on src/Sources/Code/Module.cpp
> +	struct Client * clint;
good

2024-09-05 00:08 UTC, cpuwolf commented on src/Sources/Code/Module.cpp
> +	struct Client * clint;
got it

2024-09-05 00:13 UTC, cpuwolf commented on src/Sources/Code/Module.cpp
> -	std::string Name;
I have dedicated commit "[relocate struct SimVar->Name to ReadRPNCode->Code](https://github.com/MobiFlight/MobiFlight-WASM-Module/pull/27/commits/45144941ecc63c9baa7fdfc0d964ac43a5620691)"

2024-09-05 00:17 UTC, cpuwolf commented on src/Sources/Code/Module.cpp
> +		WriteSimVar(simVar, simVar.clint);
yes

2024-09-07 19:19 UTC, DocMoebiuz commented on src/Sources/Code/Module.cpp
> -	std::string Name;
But it is missing now in the log statements which is unfortunate.

2024-09-07 19:20 UTC, DocMoebiuz commented
@cpuwolf you marked some of the comments as resolved but you might not have pushed your changes yet.

2024-09-07 23:48 UTC, cpuwolf commented
> @cpuwolf you marked some of the comments as resolved but you might not have pushed your changes yet.

should I resubmit the pull? I am expecting Github can do online review and revise the code realtime

2024-09-08 04:44 UTC, DocMoebiuz commented
You have to make the changes in your branch and simply push the branch again. The PR will automatically update then. But simply resolving the conversation doesn't do it.

2024-10-23 02:47 UTC, cpuwolf commented
@DocMoebiuz I have uploaded revised version

2025-09-19 23:07 UTC, cpuwolf commented
This patch is stable because we have 1000+ customers who have been using these changes over a year

2025-11-24 23:28 UTC, closed without merging